[versions]
kotlin = "2.2.21"
okhttp = "5.3.0"
java-websocket = "1.6.0"
fastjson = "2.0.60"
kotlin-logging = "7.0.3"
logback = "1.5.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
java-websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "java-websocket" }
fastjson-kotlin = { group = "com.alibaba.fastjson2", name = "fastjson2-kotlin", version.ref = "fastjson" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
